apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels: 
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: gcr.io/atlantean-axon-346612/webapp
        ports:
        - containerPort: 5000