apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce # Permissão para ler e escrever um pod por vez
  gcePersistentDisk:
    pdName: pv-disk # Nome do disco criado no cloud
  storageClassName: standard